# Generated by Django 3.1.7 on 2021-04-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210401_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
